// Downloads the real 78s listed in src/data/records.json into public/records/,
// and writes public/records/CREDITS.md from the same list.
//
//   npm run records            -> fetch any missing records
//   npm run records -- --force -> fetch them all again
//   npm run records -- --credits -> only rewrite CREDITS.md
//
// With ffmpeg on the PATH, each side is converted to a small mono MP3 with leading
// silence trimmed and loudness evened out. Without ffmpeg the original file is kept.
// Downloads use Node's fetch, falling back to curl (handy behind proxies).
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync, renameSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';

const OUT = 'public/records';
const { records } = JSON.parse(readFileSync('src/data/records.json', 'utf8'));
const force = process.argv.includes('--force');
const creditsOnly = process.argv.includes('--credits');
mkdirSync(OUT, { recursive: true });

const hasFfmpeg = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' }).status === 0;

async function download(url, path) {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  } catch (e) {
    const curl = spawnSync('curl', ['-sSfL', '--retry', '2', '-o', path, url], { stdio: ['ignore', 'ignore', 'inherit'] });
    if (curl.status !== 0) throw new Error(`fetch: ${e.message}; curl exit ${curl.status ?? 'missing'}`);
  }
}
let failed = 0;

if (!creditsOnly) {
  if (!hasFfmpeg) console.log('ffmpeg not found: keeping original files (bigger, unnormalized).');
  for (const r of records) {
    const dest = join(OUT, r.file);
    if (existsSync(dest) && !force) {
      console.log(`have  ${r.file}`);
      continue;
    }
    const url = `https://archive.org/download/${r.archiveId}/${encodeURIComponent(r.sourceFile)}`;
    try {
      const tmp = join(OUT, `.${r.file}.orig`);
      await download(url, tmp);
      if (hasFfmpeg) {
        const ff = spawnSync('ffmpeg', [
          '-y', '-loglevel', 'error', '-i', tmp,
          '-ac', '1', '-ar', '22050',
          '-af', 'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.2,loudnorm=I=-18:TP=-2:LRA=11',
          '-codec:a', 'libmp3lame', '-b:a', '64k', dest,
        ], { stdio: 'inherit' });
        rmSync(tmp, { force: true });
        if (ff.status !== 0) throw new Error('ffmpeg failed');
      } else {
        renameSync(tmp, dest);
      }
      console.log(`got   ${r.file}  (${r.title}, ${r.performer}, ${r.year})`);
    } catch (e) {
      failed++;
      console.log(`FAIL  ${r.file}: ${e.message ?? e} (${url})`);
    }
  }
}

// Credits, generated from the catalog so they can't drift.
const lines = [
  '# Record credits',
  '',
  'Every record in this folder is a public-domain sound recording: first published in the',
  'United States before 1926, of a song published before 1931. Transfers are from the',
  'Internet Archive\'s Great 78 Project. Public-domain status outside the US may differ.',
  '',
  'Generated by `npm run records` from `src/data/records.json`. Do not edit by hand.',
  '',
  '| Title | Performer | Year | Label | Song | Source |',
  '| --- | --- | --- | --- | --- | --- |',
  ...records.map((r) => `| ${r.title} | ${r.performer} | ${r.year} | ${r.label} | ${r.composer} | https://archive.org/details/${r.archiveId} |`),
  '',
];
writeFileSync(join(OUT, 'CREDITS.md'), lines.join('\n'));
console.log(`wrote ${OUT}/CREDITS.md`);
if (failed) {
  console.log(`\n${failed} record(s) failed. The game plays a synthesized stand-in for any missing file.`);
  process.exit(1);
}
